backend:
  name: github
  repo: andreipetroww-oss/manufarm
  branch: main
  client_id: <ВOv23liUJ8xZ5K7NzGHJH>

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: home
    label: Главная
    files:
      - file: "content/home.json"
        name: home_content
        label: Настройки
        fields:
          - {label: Заголовок, name: hero_title, widget: string}
          - {label: Подзаголовок, name: hero_subtitle, widget: string}
          - {label: Кнопка, name: cta_text, widget: string}


