backend:
  name: github
  repo: andreipetroww-oss/manufarm
  branch: main
  auth_type: implicit
  base_url: https://manufarm.netlify.app
  auth_endpoint: oauth/authorize



media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "home"
    label: "Главная страница"
    files:
      - file: "content/home.json"
        label: "Тексты сайта"
        name: "home_content"
        fields:
          - { label: "Главный заголовок", name: "hero_title", widget: "string" }
          - { label: "Подзаголовок", name: "hero_subtitle", widget: "string" }
          - { label: "Текст кнопки", name: "cta_text", widget: "string" }


